# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in punch.gemspec
# gemspec

group :development do
  gem "rake"
  gem "minitest"
  gem "punch", "~> 0.2.2", git: "https://github.com/nvoynov/punch.git"
  gem "clean", "~> 0.3.1", git: "https://github.com/nvoynov/clean.git"
end
