# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in punch.gemspec
# gemspec

group :development do
  gem "rake"
  gem "minitest"
  gem "punch", git: "https://github.com/nvoynov/punch.git"
end
