# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in punch.gemspec
# gemspec

group :development do
  gem "rake"
  gem "minitest"
  # @todo try to use local repository instead of remote
  # [Bundler Config. Local Git Repos](https://bundler.io/v2.4/man/bundle-config.1.html)
  gem "punch", git: "https://github.com/nvoynov/punch.git"
end
