#!/usr/bin/env ruby

require "bundler/setup"
require "punch/cli"
require "punch/plugins"
include Punch

LoggerPlug.object = Punch::Logger.new('punch.log')

if ARGV.empty?
  CLI.banner
  exit
end

command = ARGV.shift
command.downcase

case command
when /new/   # create new punched
  CLI.folder(ARGV.shift)
when /(entity|service|plugin)/
  CLI.source(*ARGV.unshift(command))
when /preview/ # for entities and services only
  CLI.preview(*ARGV)
when /basics/
  CLI.basics
when /samples/
  CLI.samples
when /domain/
  CLI.domain
when 'status'
  CLI.status
else
  puts "Sorry, didn't get you"
  CLI.banner
end
